events { worker_connections 1024; }

http {
    # THIS LINE IS THE MAGIC: It adds the 'upstream_addr' to the log
    log_format custom '$remote_addr - $remote_user [$time_local] '
                      '"$request" $status $body_bytes_sent '
                      '"$http_referer" "$http_user_agent" '
                      'SERVER_IP: $upstream_addr';

    upstream helpdesk_cluster {
        server helpdesk-app-1:3000;
        server helpdesk-app-2:3000;
        server helpdesk-app-3:3000;
    }

    server {
        listen 80;
        # Tell Nginx to use our custom format
        access_log /var/log/nginx/access.log custom;

        location / {
            proxy_pass http://helpdesk_cluster;
        }
    }
}